---
title: "Transforming DistWin projects to the `R` environment"
author: "Eric Rexstad"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Vignette Title}
  %\VignetteEngine{knitr::rmarkdown}
  \usepackage[utf8]{inputenc}
---

# Migration of DistWin analysis structure to R

The Windows-based GUI software for conducting distance sampling analysis (*Distance for Windows*, heretofore *DistWin*) has been the industry-standard for two decades.  Our development work continues to incorporate state-of-the-art analytical methods for software users.  Most of that software development takes place in the `R` language.

As a portal for statisticans and biologists who have existing `DistWin` projects, the `readdst` package was created.  It was originally intended as an *in-house* testing tool to enable comparison of analysis results of newly-developed analysis software, with results produced by `Distwin`. The purpose of the package is to convert data and analyses stored in `DistWin` projects into data objects and function calls for analysis using `R`.

This vignette is intended to give a few examples of the capabilities of `readdst`.  Readers of this vignette should have some familiarity with the organisation of `DistWin` projects along with functions in the `mrds` library for fitting detection functions.

# Structure of `DistWin` project

`DistWin` projects carry not only the data collected in the field, but also survey descriptions, data filters, model definitions and analysis results.

* Survey information includes point or line transect types, whether animals were recorded as individuals or clusters, whether perpendicular distances or radial distances and angles were recorded.
* Data filters possess information about sightings to include in analysis (truncation distance, species indicators for multi-species surveys)
* Model definitions describe the key function and adjustment term combinations to be fitted as the detection function, whether data will be combined across strata for detection function fitting, etc.
* Analysis results are the product of submitting the survei/filter/model combination to the analysis engines in `DistWin`.

# Example project files to transform

There are two projects that come with the distribution of `DistWin` located in `My Documents\My Distance Projects\Sample Projects` I will use to demonstrate the use of `DistWin`.  In addition, I have taken another project that ships with `DistWin`, `Stratify example`, renamed it `Vignette-stratify` and added further analyses to that project for use in this vignette.  This third example ships with the `readdst` R package and is found in the library folder associated with the `readdst` package (see below).

## Ducknest
This project consists of an artificial example in which duck nest objects are collected as *binned* data.  The units of the project are non-SI miles and feet.  There is one non-default data filter, specifying a 6 foot perpendicular truncation distance.  There are four model definitions present:

* half-normal with cosine adjustment
* hazard rate with polynomial adjustment
* uniform with cosine adjustment, and
* half-normal with Hermite adjustment.

## Vignette-stratify
Synthetic line transect data, units of measure in non-SI units (effort and perpendicular distance in nautical miles).  Animals were detected in groups, so cluster size enters into the calculation of animal density.  The project contains a multiplier derived from an external estimate of $\widehat{g(0)}$, but for purposes of this vignette, the use of the multiplier has been removed from the `DistWin` analysis.

The study area also contains two types of habitat and the design incorporated habitat information.  Consequently, the brief analysis focuses upon whether it is most parsimonious to fit habitat-specific detection functions, or whether a single detection function pooled across habitat types.

## Amakihi
This project demonstrates the use of the MRDS (multiple covariate) analysis engine in conjunction with a point transect sampling survey (using conventional SI measurement units).  The analyses present in the project represent 16 model results presented in Marques et al. (2007).  All analyses employ a data filter specifying an 82.5m truncation distance.

# Conversion process

## Additional analysis of converted project

# Comparing results of `DistWin` and R analyses

# Migrations not performed by `readdst`